# Entity attributes
ATTR_DEVICE_CLASS = "device_class"
ATTR_ENTITY_PICTURE = "entity_picture"
ATTR_FRIENDLY_NAME = "friendly_name"
ATTR_GPS_ACCURACY = "gps_accuracy"
ATTR_ICON = "icon"
ATTR_LATITUDE = "latitude"
ATTR_LONGITUDE = "longitude"


# Browsers
BROWSER_CHROME = "Chrome"
BROWSER_FIREFOX = "Firefox"
BROWSER_MOBILE_APP = "Mobile App"


# Notification channels
CHANNEL_ATTACKS = "Attacks"
CHANNEL_GARAGE_DOOR_ACTIVITY = "Garage Door Activity"
CHANNEL_LOCATION_UPDATES = "Location Updates"
CHANNEL_LOCK_ACTIVITY = "Lock Activity"


# Computers
COMPUTER_JACOB_S_DESKTOP = "jacob_s_desktop"
COMPUTER_JACOB_S_SCHOOL_LAPTOP = "jacob_s_school_laptop"


# YAML configuration keys
CONF_ACTION = "action"
CONF_ACTION_DATA = "action_data"
CONF_ACTIONS = "actions"
CONF_ACTIVE = "active"
CONF_ALIASES = "aliases"
CONF_AUTHENTICATIONREQUIRED = "authenticationRequired"
CONF_BADGES = "badges"
CONF_CARD_MOD = "card_mod"
CONF_CARD = "card"
CONF_CARDS = "cards"
CONF_CHANNEL = "channel"
CONF_CLICKACTION = "clickAction"
CONF_CONTROLS = "controls"
CONF_COVERS = "covers"
CONF_CRITICAL = "critical"
CONF_DARK = "dark"
CONF_DASHBOARDS = "dashboards"
CONF_DATA = "data"
CONF_DATETIME = "datetime"
CONF_DEVICEID = "deviceID"
CONF_DEVICE_TRACKERS = "device_trackers"
CONF_DISCOVERY = "discovery"
CONF_DOMAINS = "domains"
CONF_DURATION = "duration"
CONF_ENTITIES = "entities"
CONF_ENTITY = "entity"
CONF_ENTITY_CONFIG = "entity_config"
CONF_ENTITY_ID = "entity_id"
CONF_EXPOSE = "expose"
CONF_EXTRA_ARGUMENTS = "extra_arguments"
CONF_FILENAME = "filename"
CONF_FILTER = "filter"
CONF_GROUP = "group"
CONF_HAPTIC = "haptic"
CONF_HAS_TIME = "has_time"
CONF_HAS_DATE = "has_date"
CONF_HEAD = "head"
CONF_HIDE = "hide"
CONF_HIDE_STATE = "hide_state"
CONF_HOST = "host"
CONF_ICON = "icon"
CONF_ICON_URL = "icon_url"
CONF_ID = "id"
CONF_IMAGE = "image"
CONF_IMPORTANCE = "importance"
CONF_INCLUDE = "include"
CONF_INCLUDE_ENTITIES = "include_entities"
CONF_INFO = "info"
CONF_INITIAL = "initial"
CONF_INPUT = "input"
CONF_ITEMS = "items"
CONF_LABEL = "label"
CONF_LATITUDE = "latitude"
CONF_LIGHT = "light"
CONF_LONGITUDE = "longitude"
CONF_MAX = "max"
CONF_MESSAGE = "message"
CONF_MIN = "min"
CONF_MODE = "mode"
CONF_MODES = "modes"
CONF_NAME = "name"
CONF_PANEL = "panel"
CONF_OPEN = "open"
CONF_OPTION = "option"
CONF_OPTIONS = "options"
CONF_PATH = "path"
CONF_PLATFORM = "platform"
CONF_POPUP_CARDS = "popup_cards"
CONF_POWER = "power"
CONF_PREFIX = "prefix"
CONF_PRIORITY = "priority"
CONF_PROGRESS = "progress"
CONF_PUSH = "push"
CONF_RADIUS = "radius"
CONF_REMOTE = "remote"
CONF_RESOURCES = "resources"
CONF_ROOM = "room"
CONF_SERVICE_NAME = "service_name"
CONF_SHOW_HEADER_TOGGLE = "show_header_toggle"
CONF_SHOWS_COMPASS = "shows_compass"
CONF_SHOWS_POINTS_OF_INTEREST = "shows_points_of_interest"
CONF_SHOWS_SCALE = "shows_scale"
CONF_SHOWS_TRAFFIC = "shows_traffic"
CONF_SHOWS_USER_LOCATION = "shows_user_location"
CONF_SOUND = "sound"
CONF_SUBJECT = "subject"
CONF_SUBTITLE = "subtitle"
CONF_STATE = "state"
CONF_STATE_COLOR = "state_color"
CONF_STEP = "step"
CONF_SOURCE = "source"
CONF_STYLE = "style"
CONF_SWITCH = "switch"
CONF_TAG = "tag"
CONF_THEMES = "themes"
CONF_TIME_MEMORY = "time_memory"
CONF_TITLE = "title"
CONF_TOGGLE = "toggle"
CONF_TTL = "ttl"
CONF_TV = "tv"
CONF_TYPE = "type"
CONF_UNIT_OF_MEASUREMENT = "unit_of_measurement"
CONF_URL = "url"
CONF_USER_ID = "user_id"
CONF_VALUE = "value"
CONF_VIEWS = "views"
CONF_VOLUME = "volume"
CONF_VOLUME_STATELESS = "volume_stateless"


# Data affixes (used by the custom backend and secrets file, sometimes based on slug parts that are out of my control though)
DATA_ACCESS_CONTROL_LOCK_JAMMED = "access_control_lock_jammed"
DATA_ACCESS_CONTROL_LOCK_STATE = "access_control_lock_state"
DATA_ACTION = "action"
DATA_ACTIONS = "actions"
DATA_ALARM = "alarm"
DATA_ALARMLEVEL = "alarmlevel"
DATA_ALARMTYPE = "alarmtype"
DATA_AUDIO = "audio"
DATA_BEDTIME_SHIFT = "bedtime_shift"
DATA_BLINDS = "blinds"
DATA_BLUE = "blue"
DATA_BROWSER_MOD = "browser_mod"
DATA_BROWSERS = "browsers"
DATA_CAMERA = "camera"
DATA_CAUSE = "cause"
DATA_CHANNEL = "channel"
DATA_CHROMECAST = "chromecast"
DATA_CLOSE_GARAGE_DOOR = "close_garage_door"
DATA_COMES_FROM_ROKU = "comes_from_roku"
DATA_COMES_FROM_SWITCH = "comes_from_switch"
DATA_COMPUTER = "computer"
DATA_COMPUTERS = "computers"
DATA_COORDINATES = "coordinates"
DATA_CURRENT_SENSOR = "current_sensor"
DATA_DATETIME = "datetime"
DATA_DEVICES = "devices"
DATA_FIRST_ALARM_TODAY = "first_alarm_today"
DATA_FULL_NAME = "full_name"
DATA_GARAGE_DOORS = "garage_doors"
DATA_GROUP = "group"
DATA_GROUP_MEMBERS = "group_members"
DATA_HAS_DISPLAY = "has_display"
DATA_HOME = "home"
DATA_HOST = "host"
DATA_ICON = "icon"
DATA_ID = "id"
DATA_IMAGE = "image"
DATA_IN_VIEW = "in_view"
DATA_INDICATOR_LIGHTS = "indicator_lights"
DATA_IS_TV = "is_tv"
DATA_LABEL = "label"
DATA_LAST_ALARM = "last_alarm"
DATA_LATITUDE = "latitude"
DATA_LEISURE = "leisure"
DATA_LIGHTS = "lights"
DATA_LOCK_CODE = "lock_code"
DATA_LOCK_SLOT = "lock_slot"
DATA_LOCK_SLOTS = "lock_slots"
DATA_LOCKS = "locks"
DATA_LOW_BATTERY_LEVEL = "low_battery_level"
DATA_LONGITUDE = "longitude"
DATA_MAP = "map"
DATA_MESSAGE = "message"
DATA_MESSAGE_HTML = "message_html"
DATA_MOBILE_APP = "mobile_app"
DATA_NAME = "name"
DATA_NEXT_ALARM = "next_alarm"
DATA_NICKNAME = "nickname"
DATA_OPEN_GARAGE_DOOR = "open_garage_door"
DATA_OS = "os"
DATA_OSES = "oses"
DATA_PEOPLE = "people"
DATA_PERSON = "person"
DATA_PERSONALIZED = "personalized"
DATA_PHONE = "phone"
DATA_PHONES = "phones"
DATA_PHOTO = "photo"
DATA_POWER_SENSOR = "power_sensor"
DATA_PRIORITY = "priority"
DATA_PUSH = "push"
DATA_RADIUS = "radius"
DATA_RED = "red"
DATA_REPLACE = "replace"
DATA_REQUIRE_DEVICE_UNLOCK = "require_device_unlock"
DATA_ROKU = "roku"
DATA_ROOM = "room"
DATA_ROOMS = "rooms"
DATA_ROOM_WITH_LIMITED_ACCESS = "room_with_keypad"
DATA_ROOM_WITH_FREE_ACCESS = "room_with_twist_knob"
DATA_SHORT_NAME = "short_name"
DATA_SLEEP_DURATION = "sleep_duration"
DATA_SLUG = "slug"
DATA_SSML = "ssml"
DATA_STREAM_SOURCE = "stream_source"
DATA_TABLET = "tablet"
DATA_TABLETS = "tablets"
DATA_TAILWIND = "tailwind"
DATA_TEXT = "text"
DATA_THE_CURRENT_STATUS_OF_THE_DOOR = "the_current_status_of_the_door"
DATA_TITLE = "title"
DATA_TITLE_HTML = "title_html"
DATA_TPLINK_LIGHT = "tplink_light"
DATA_TPLINK_SWITCH = "tplink_switch"
DATA_TTS = "tts"
DATA_USER_ID = "user_id"
DATA_VIDEO_QUALITY = "video_quality"
DATA_VOLTAGE_SENSOR = "voltage_sensor"
DATA_WIND_DOWN_BEFORE_FALLING_ASLEEP_DURATION = "wind_down_before_falling_asleep_duration"
DATA_WINDOW = "window"
DATA_ZONE = "zone"


# Device classes
DEVICE_CLASS_BATTERY = "battery"
DEVICE_CLASS_BLINDS = "blinds"
DEVICE_CLASS_CURRENT = "current"
DEVICE_CLASS_GARAGE = "garage"
DEVICE_CLASS_POWER = "power"
DEVICE_CLASS_PROBLEM = "problem"
DEVICE_CLASS_SPEAKER = "speaker"
DEVICE_CLASS_TV = "tv"
DEVICE_CLASS_VOLTAGE = "voltage"
DEVICE_CLASS_WINDOW = "window"


# Device types
DEVICE_TYPE_COMPUTER = "computer"
DEVICE_TYPE_LIGHT = "light"
DEVICE_TYPE_PHONE = "phone"
DEVICE_TYPE_SPEAKER = "speaker"
DEVICE_TYPE_TABLET = "tablet"

DEVICE_TYPES = [DEVICE_TYPE_COMPUTER, DEVICE_TYPE_LIGHT, DEVICE_TYPE_PHONE, DEVICE_TYPE_SPEAKER, DEVICE_TYPE_TABLET]


# Domains
DOMAIN_BINARY_SENSOR = "binary_sensor"
DOMAIN_BROWSER_MOD = "browser_mod"
DOMAIN_CAMERA = "camera"
DOMAIN_COVER = "cover"
DOMAIN_CUSTOM_BACKEND = "custom_backend"
DOMAIN_DEVICE_TRACKER = "device_tracker"
DOMAIN_FRONTEND = "frontend"
DOMAIN_HOMEKIT = "homekit"
DOMAIN_INPUT_DATETIME = "input_datetime"
DOMAIN_INPUT_NUMBER = "input_number"
DOMAIN_INPUT_SELECT = "input_select"
DOMAIN_INPUT_TEXT = "input_text"
DOMAIN_LIGHT = "light"
DOMAIN_LOCK = "lock"
DOMAIN_LOVELACE = "lovelace"
DOMAIN_MEDIA_PLAYER = "media_player"
DOMAIN_NOTIFY = "notify"
DOMAIN_TPLINK = "tplink"
DOMAIN_TTS = "tts"
DOMAIN_PERSON = "person"
DOMAIN_RECORDER = "recorder"
DOMAIN_REMOTE = "remote"
DOMAIN_SENSOR = "sensor"
DOMAIN_SWITCH = "switch"
DOMAIN_ZONE = "zone"


# Event types
EVENT_TYPE_HOMEASSISTANT_START = "homeassistant_start"
EVENT_TYPE_MOBILE_APP_NOTIFICATION_ACTION = "mobile_app_notification_action"


# Garage doors
GARAGE_DOOR_GARAGE_DOOR = "garage_door"


# Icons
ICON_MDI_ALARM = "mdi:alarm"
ICON_MDI_BED = "mdi:bed"
ICON_MDI_BLINDS = "mdi:blinds"
ICON_MDI_BLINDS_OPEN = "mdi:blinds-open"
ICON_MDI_CANDLE = "mdi:candle"
ICON_MDI_CAR_LIGHT_DIMMED = "mdi:car-light-dimmed"
ICON_MDI_CART = "mdi:cart"
ICON_MDI_CCTV = "mdi:cctv"
ICON_MDI_CEILING_LIGHT = "mdi:ceiling-light"
ICON_MDI_CELLPHONE = "mdi:cellphone"
ICON_MDI_CELLPHONE_SOUND = "mdi:cellphone-sound"
ICON_MDI_CELLPHONE_TEXT = "mdi:cellphone-text"
ICON_MDI_CURRENT_AC = "mdi:current-ac"
ICON_MDI_DEVICES = "mdi:devices"
ICON_MDI_FIREPLACE = "mdi:fireplace"
ICON_MDI_FLASH = "mdi:flash"
ICON_MDI_FLOOR_LAMP = "mdi:floor-lamp"
ICON_MDI_FLOOR_PLAN = "mdi:floor-plan"
ICON_MDI_FOUNTAIN = "mdi:fountain"
ICON_MDI_GARAGE = "mdi:garage"
ICON_MDI_HAMBURGER = "mdi:hamburger"
ICON_MDI_HOME_ACCOUNT = "mdi:home-account"
ICON_MDI_LAMP = "mdi:lamp"
ICON_MDI_LED_VARIANT_ON = "mdi:led-variant-on"
ICON_MDI_LIGHTBULB_CFL = "mdi:lightbulb-cfl"
ICON_MDI_LIGHTBULB_GROUP = "mdi:lightbulb-group"
ICON_MDI_LIGHTBULB_ON = "mdi:lightbulb-on"
ICON_MDI_LOCK = "mdi:lock"
ICON_MDI_LOCK_ALERT = "mdi:lock-alert"
ICON_MDI_MAP_MARKER_CIRCLE = "mdi:map-marker-circle"
ICON_MDI_MIRROR = "mdi:mirror"
ICON_MDI_MONITOR_DASHBOARD = "mdi:monitor-dashboard"
ICON_MDI_MONITOR_EYE = "mdi:monitor-eye"
ICON_MDI_MONITOR_SPEAKER = "mdi:monitor-speaker"
ICON_MDI_OUTDOOR_LAMP = "mdi:outdoor-lamp"
ICON_MDI_PIZZA = "mdi:pizza"
ICON_MDI_REMOVE_TV = "mdi:remote-tv"
ICON_MDI_RICE = "mdi:rice"
ICON_MDI_SINE_WAVE = "mdi:sine-wave"
ICON_MDI_SPEAKER = "mdi:speaker"
ICON_MDI_SPEAKER_MULTIPLE = "mdi:speaker-wireless"
ICON_MDI_SPEAKER_WIRELESS = "mdi:speaker-wireless"
ICON_MDI_TACO = "mdi:taco"
ICON_MDI_TABLET = "mdi:tablet"
ICON_MDI_TABLET_DASHBOARD = "mdi:tablet-dashboard"
ICON_MDI_TARGET_ACCOUNT = "mdi:target-account"
ICON_MDI_TELEVISION = "mdi:television"
ICON_MDI_TELEVISION_AMBIENT_LIGHT = "mdi:television-ambient-light"
ICON_MDI_VIEW_DASHBOARD = "mdi:view-dashboard"
ICON_MDI_WALL_SCONCE_FLAT = "mdi:wall-sconce-flat"
ICON_MDI_WALL_SCONCE_ROUND_VARIANT = "mdi:wall-sconce-round-variant"
ICON_MDI_WINDOW_CLOSED_VARIANT = "mdi:window-closed-variant"
ICON_MDI_WINDOW_OPEN_VARIANT = "mdi:window-open-variant"
ICON_MDX_GOOGLE_HOME_MINI = "mdx:google-home-mini"
ICON_MDX_LENOVO_SMART_DISPLAY = "mdx:lenovo-smart-display"


# Images
IMAGE_ACCESS_DENIED_COLOR = "/local/graphic/access-denied-color.png"
IMAGE_ALARM_CLOCK_COLOR = "/local/graphic/alarm-clock-color.png"
IMAGE_CALL_LIST_COLOR = "/local/graphic/call-list-color.png"
IMAGE_COMPACT_CAMERA_COLOR = "/local/graphic/compact-camera-color.png"
IMAGE_DEFENSE_COLOR = "/local/graphic/defense-color.png"
IMAGE_EXPIRED_COLOR = "/local/graphic/expired-color.png"
IMAGE_FRAUD_COLOR = "/local/graphic/fraud-color.png"
IMAGE_FUTURE_COLOR = "/local/graphic/future-color.png"
IMAGE_GARAGE_DOOR_CLOSED_COLOR = "/local/graphic/garage-door-closed-color.png"
IMAGE_GARAGE_DOOR_OPEN_COLOR = "/local/graphic/garage-door-open-color.png"
IMAGE_GOOD_PINCODE_COLOR = "/local/graphic/good-pincode-color.png"
IMAGE_KEYPAD_COLOR = "/local/graphic/keypad-color.png"
IMAGE_LIGHT_ON_COLOR = "/local/graphic/light-on-color.png"
IMAGE_LIST_VIEW_COLOR = "/local/graphic/list-view-color.png"
IMAGE_LOCK_LOCKED_COLOR = "/local/graphic/lock-locked-color.png"
IMAGE_LOCK_UNLOCKED_COLOR = "/local/graphic/lock-unlocked-color.png"
IMAGE_OFFLINE_COLOR = "/local/graphic/offline-color.png"
IMAGE_OPEN_WINDOW_COLOR = "/local/graphic/open-window-color.png"
IMAGE_PLACE_MARKER_COLOR = "/local/graphic/place-marker-color.png"
IMAGE_ROOT_SERVER_COLOR = "/local/graphic/root-server-color.png"
IMAGE_SENSOR_COLOR = "/local/graphic/sensor-color.png"
IMAGE_STORMY_WEATHER_COLOR = "/local/graphic/stormy-weather-color.png"
IMAGE_SUBWOOFER_COLOR = "/local/graphic/subwoofer-color.png"
IMAGE_TEAM_COLOR = "/local/graphic/team-color.png"
IMAGE_TIMER_COLOR = "/local/graphic/timer-color.png"
IMAGE_TV_SHOW_COLOR = "/local/graphic/tv-show-color.png"
IMAGE_WEB_SHIELD_COLOR = "/local/graphic/web-shield-color.png"
IMAGE_WORKSTATION_COLOR = "/local/graphic/workstation-color.png"
IMAGE_WRONG_PINCODE_COLOR = "/local/graphic/wrong-pincode-color.png"
IMAGE_WYZE_LOGO = "/local/graphic/wyze-logo.png"


# Lights
LIGHT_PORCH = "porch"


# Locks
LOCK_DOOR_TO_THE_GARAGE = "door_to_the_garage"
LOCK_FRONT_DOOR = "front_door"


# Operating systems
OS_ANDROID = "Android"
OS_IOS = "iOS"
OS_MACOS = "macOS"
OS_WINDOWS = "Windows"


# People
PERSON_BAKA = "baka"
PERSON_GARY = "gary"
PERSON_GLORIA = "gloria"
PERSON_HELGA = "helga"
PERSON_JACKSON = "jackson"
PERSON_JACOB = "jacob"
PERSON_JENNA = "jenna"
PERSON_JILLIAN = "jillian"
PERSON_JORDAN = "jordan"
PERSON_JUSTIN = "justin"
PERSON_MATT = "matt"


# Phones
PHONE_JACOB_S_HTC_U11 = "jacob_s_htc_u11"
PHONE_JENNA_S_IPHONE_XR = "jenna_s_iphone_xr"
PHONE_MATT_S_ONEPLUS_8 = "matt_s_oneplus_8"


# Platforms
PLATFORM_FFMPEG = "ffmpeg"
PLATFORM_GOOGLE_TRANSLATE = "google_translate"
PLATFORM_GROUP = "group"
PLATFORM_SWITCH = "switch"
PLATFORM_TEMPLATE = "template"


# Priorities (for the notification system)
PRIORITY_LOW = "low"
PRIORITY_NORMAL = "normal"
PRIORITY_URGENT = "urgent"
PRIORITY_EMERGENCY = "emergency"

PRIORITIES = [PRIORITY_LOW, PRIORITY_NORMAL, PRIORITY_URGENT, PRIORITY_EMERGENCY]


# Push sounds
PUSH_SOUND_3RD_PARTY_CRITICAL = "3rd_party_critical.caf"
PUSH_SOUND_ALARM_NIGHTSTAND_HAPTIC = "Alarm_Nightstand_Haptic.caf"
PUSH_SOUND_AUTOUNLOCK_HAPTIC = "AutoUnlock_Haptic.caf"
PUSH_SOUND_DEFAULT = "default"
PUSH_SOUND_SWTEST1_HAPTIC = "SwTest1_Haptic.caf"

# Rooms
ROOM_BACKYARD = "Backyard"
ROOM_BAKA_S_BEDROOM = "Baka's Bedroom"
ROOM_BASEMENT = "Basement"
ROOM_BATHROOM = "Bathroom"
ROOM_DRIVEWAY = "Driveway"
ROOM_EAST_YARD = "East Yard"
ROOM_FRONT_ROOM = "Front Room"
ROOM_FRONT_YARD = "Front Yard"
ROOM_GARAGE = "Garage"
ROOM_HALLWAY = "Hallway"
ROOM_JACOB_S_BEDROOM = "Jacob's Bedroom"
ROOM_JENNA_S_BEDROOM = "Jenna's Bedroom"
ROOM_KITCHEN = "Kitchen"
ROOM_LAUNDRY_ROOM = "Laundry Room"
ROOM_MATT_S_BEDROOM = "Matt's Bedroom"
ROOM_WEST_YARD = "West Yard"

ROOMS_AT_BAKA_S_HOUSE = [ROOM_BACKYARD, ROOM_BAKA_S_BEDROOM, ROOM_BASEMENT, ROOM_BATHROOM, ROOM_DRIVEWAY, ROOM_EAST_YARD, ROOM_FRONT_ROOM, ROOM_FRONT_YARD, ROOM_GARAGE, ROOM_HALLWAY, ROOM_JACOB_S_BEDROOM, ROOM_JENNA_S_BEDROOM, ROOM_KITCHEN, ROOM_LAUNDRY_ROOM, ROOM_MATT_S_BEDROOM, ROOM_WEST_YARD]


# Services
SERVICE_CLOSE_COVER = "close_cover"
SERVICE_GENERATE_CODE = "generate_code"
SERVICE_GOOGLE_SAY = "google_say"
SERVICE_LOCK = "lock"
SERVICE_NOTIFY = "notify"
SERVICE_OPEN_COVER = "open_cover"
SERVICE_SELECT_OPTION = "select_option"
SERVICE_SET_DATETIME = "set_datetime"
SERVICE_SET_VALUE = "set_value"
SERVICE_TOAST = "toast"
SERVICE_UNLOCK = "unlock"


# Data shared in the hass.data store (in memory)
SHARED_EVERPRESENT_NOTIFICATION_ACTIONS = "everpresent_notification_actions"
SHARED_NOTIFICATION_ACTIONS = "notification_actions"
SHARED_REMOTE_UNLOCKING = "remote_unlocking"


# States
STATE_CLOSED = "closed"
STATE_CLOSING = "closing"
STATE_LOCKED = "locked"
STATE_OPEN = "open"
STATE_OPENING = "opening"
STATE_UNKNOWN = "unknown"
STATE_UNLOCKED = "unlocked"


# Tablets
TABLET_MATT_S_2015_IPAD_PRO = "matt_s_2015_ipad_pro"


# Lovelace theme values
THEME_VALUE_ACCENT_COLOR = "accent-color"
THEME_VALUE_APP_HEADER_BACKGROUND_COLOR = "app-header-background-color"
THEME_VALUE_APP_HEADER_TEXT_COLOR = "app-header-text-color"
THEME_VALUE_CARD_BACKGROUND_COLOR = "card-background-color"
THEME_VALUE_CODEMIRROR_ATOM = "codemirror-atom"
THEME_VALUE_CODEMIRROR_COMMENT = "codemirror-comment"
THEME_VALUE_CODEMIRROR_KEYWORD = "codemirror-keyword"
THEME_VALUE_CODEMIRROR_NUMBER = "codemirror-number"
THEME_VALUE_CODEMIRROR_PROPERTY = "codemirror-property"
THEME_VALUE_CODEMIRROR_STRING = "codemirror-string"
THEME_VALUE_DISABLED_TEXT_COLOR = "disabled-text-color"
THEME_VALUE_ERROR_COLOR = "error-color"
THEME_VALUE_HA_CARD_BORDER_RADIUS = "ha-card-border-radius"
THEME_VALUE_PAPER_SLIDER_KNOB_COLOR = "paper-slider-knob-color"
THEME_VALUE_PRIMARY_BACKGROUND_COLOR = "primary-background-color"
THEME_VALUE_PRIMARY_COLOR = "primary-color"
THEME_VALUE_PRIMARY_FONT_FAMILY = "primary-font-family"
THEME_VALUE_PRIMARY_TEXT_COLOR = "primary-text-color"
THEME_VALUE_SECONDARY_BACKGROUND_COLOR = "secondary-background-color"
THEME_VALUE_SECONDARY_TEXT_COLOR = "secondary-text-color"
THEME_VALUE_SECTION_HEADER_TEXT_COLOR = "section-header-text-color"
THEME_VALUE_SUCCESS_COLOR = "success-color"
THEME_VALUE_SLIDER_COLOR = "slider-color"
THEME_VALUE_STATE_ICON_ACTIVE_COLOR = "state-icon-active-color"
THEME_VALUE_STATE_ICON_COLOR = "state-icon-color"
THEME_VALUE_TEXT_PRIMARY_COLOR = "text-primary-color"
THEME_VALUE_WARNING_COLOR = "warning-color"


# Datetime formats
TIME_FORMAT_HOUR_COLON_MINUTE = "%H:%M"
TIME_FORMAT_INPUT_DATETIME = "%Y-%m-%d %H:%M:%S"
TIME_FORMAT_PRETTY_DATE = "%A, %B %d, %Y"
TIME_FORMAT_PRETTY_TIME = "%I:%M %p"
TIME_FORMAT_PRETTY_TIME_ON_DATE = "%I:%M %p on %A, %B %d, %Y"


# Card types
TYPE_CUSTOM_FOLD_ENTITY_ROW = "custom:fold-entity-row"
TYPE_CUSTOM_MINI_MEDIA_PLAYER = "custom:mini-media-player"
TYPE_CUSTOM_ROKU_CARD = "custom:roku-card"
TYPE_CUSTOM_SLIDER_ENTITY_ROW = "custom:slider-entity-row"
TYPE_CUSTOM_TEMPLATE_ENTITY_ROW = "custom:template-entity-row"
TYPE_ENTITIES = "entities"
TYPE_SECTION = "section"


# Unit of measurement
UNIT_OF_MEASUREMENT_MINUTE = "min"

# Zones
ZONE_BAKA_S_HOUSE = "Baka's House"
ZONE_GARY_S_HOUSE = "Gary's House"
ZONE_GLORIA_S_HOUSE = "Gloria's House"
